In [1]:
import pandas as pd

In [3]:
data = pd.read_csv("./Used_fiat_500_in_Italy_dataset.csv")
data

,model,engine_power,transmission,age_in_days,km,previous_owners,lat,lon,price
0,pop,69,manual,4474,56779,2,45.071079,7.46403,4490
1,lounge,69,manual,2708,160000,1,45.069679,7.70492,4500
2,lounge,69,automatic,3470,170000,2,45.514599,9.28434,4500
3,sport,69,manual,3288,132000,2,41.903221,12.49565,4700
4,sport,69,manual,3712,124490,2,45.532661,9.03892,4790
...,...,...,...,...,...,...,...,...,...
375,lounge,69,manual,4474,55976,2,45.610050,9.24234,5500
376,lounge,69,manual,4200,134717,1,44.102020,9.82024,5500
377,lounge,69,manual,3470,113344,1,41.003799,16.87294,5500
378,pop,69,automatic,3712,130000,1,45.810501,8.96474,5500
379,lounge,99,manual,4566,96000,1,44.325890,10.83756,5500

In [9]:
data.columns

Index(['model', 'engine_power', 'transmission', 'age_in_days', 'km',
       'previous_owners', 'lat', 'lon', 'price'],
      dtype='object')

In [7]:
data.describe() #Indici statistici

,engine_power,age_in_days,km,previous_owners,lat,lon,price
count,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000
mean,73.015789,3310.265789,102196.250000,1.510526,44.257712,10.742644,5881.655263
std,9.984672,1437.555063,47115.355234,0.560244,1.767518,2.167753,2170.617946
min,69.000000,91.000000,4981.000000,1.000000,37.510872,7.320720,2890.000000
25%,69.000000,3097.250000,76611.750000,1.000000,43.514196,9.159140,4600.000000
50%,69.000000,3927.000000,112000.000000,1.000000,45.069679,10.301505,5000.000000
75%,69.000000,4322.000000,135000.000000,2.000000,45.556942,12.346788,5500.000000
max,101.000000,4719.000000,259000.000000,4.000000,46.781651,18.168011,15900.000000

In [10]:
data["price"].describe()

count      380.000000
mean      5881.655263
std       2170.617946
min       2890.000000
25%       4600.000000
50%       5000.000000
75%       5500.000000
max      15900.000000
Name: price, dtype: float64

In [11]:
data.head(10)

,model,engine_power,transmission,age_in_days,km,previous_owners,lat,lon,price
0,pop,69,manual,4474,56779,2,45.071079,7.46403,4490
1,lounge,69,manual,2708,160000,1,45.069679,7.70492,4500
2,lounge,69,automatic,3470,170000,2,45.514599,9.28434,4500
3,sport,69,manual,3288,132000,2,41.903221,12.49565,4700
4,sport,69,manual,3712,124490,2,45.532661,9.03892,4790
5,lounge,69,manual,3684,91000,1,40.774780,14.59192,4900
6,lounge,69,automatic,4353,90068,1,41.726700,13.00980,4950
7,pop,69,manual,4414,69000,2,45.056599,9.70176,5290
8,lounge,69,automatic,4322,117000,1,45.329800,10.12680,5399
9,lounge,99,manual,4566,78000,1,45.467960,9.18178,5800

In [12]:
data.tail(5)

,model,engine_power,transmission,age_in_days,km,previous_owners,lat,lon,price
375,lounge,69,manual,4474,55976,2,45.610050,9.24234,5500
376,lounge,69,manual,4200,134717,1,44.102020,9.82024,5500
377,lounge,69,manual,3470,113344,1,41.003799,16.87294,5500
378,pop,69,automatic,3712,130000,1,45.810501,8.96474,5500
379,lounge,99,manual,4566,96000,1,44.325890,10.83756,5500

In [13]:
# Selezioniamo colonne
cols = ["model", "age_in_days", "km", "price"]
data[cols]

      model  age_in_days      km  price
0       pop         4474   56779   4490
1    lounge         2708  160000   4500
2    lounge         3470  170000   4500
3     sport         3288  132000   4700
4     sport         3712  124490   4790
..      ...          ...     ...    ...
375  lounge         4474   55976   5500
376  lounge         4200  134717   5500
377  lounge         3470  113344   5500
378     pop         3712  130000   5500
379  lounge         4566   96000   5500

[380 rows x 4 columns]

In [18]:
#data[data["model"]=="star"]

In [26]:
# Selezioniamo colonne
cols = ["model", "age_in_days", "km", "price"]
selected_data = data[cols]

In [28]:
selected_data.to_clipboard() #Questo è come fare cntrl+c ! Per far la copia!

In [30]:
pd.read_clipboard() #QUesto è il cntrl + v

      model  age_in_days      km  price
0       pop         4474   56779   4490
1    lounge         2708  160000   4500
2    lounge         3470  170000   4500
3     sport         3288  132000   4700
4     sport         3712  124490   4790
..      ...          ...     ...    ...
375  lounge         4474   55976   5500
376  lounge         4200  134717   5500
377  lounge         3470  113344   5500
378     pop         3712  130000   5500
379  lounge         4566   96000   5500

[380 rows x 4 columns]

### Tutte le 500 pop con prezzo minore di 2000 euro

In [31]:
selected_data[(selected_data["model"] == "pop") & (selected_data["price"] < 4000)]

    model  age_in_days      km  price
101   pop         3957  151000   3400
102   pop         4627  148000   3500
104   pop         4658  165000   3600
108   pop         4535  125000   3750
111   pop         3774  139000   3900
112   pop         3804  110000   3900
115   pop         4322  151500   3900
117   pop         2527   82000   3950
118   pop         4383  107600   3950
120   pop         4566  173960   3990

### Ora creiamo una colonna

In [33]:
data["price_$"] = data["price"] * 1.169145
data.head()

,model,engine_power,transmission,age_in_days,km,previous_owners,lat,lon,price,price_$
0,pop,69,manual,4474,56779,2,45.071079,7.46403,4490,5249.46105
1,lounge,69,manual,2708,160000,1,45.069679,7.70492,4500,5261.15250
2,lounge,69,automatic,3470,170000,2,45.514599,9.28434,4500,5261.15250
3,sport,69,manual,3288,132000,2,41.903221,12.49565,4700,5494.98150
4,sport,69,manual,3712,124490,2,45.532661,9.03892,4790,5600.20455

### Il prezzo medio di ciascun modello di fiat 500

In [35]:
data[["model", "price"]].groupby("model").mean()

               price
model
lounge   6175.740566
pop      5618.990196
sport    5256.076923
star    10990.000000

### Prezzo minimo

In [41]:
data[["model", "price"]].groupby("model").min()

        price
model
lounge   2890
pop      3400
sport    3250
star    10990

### Per ogni modello di fiat 500, sul tipo di cambio, il numero di esemplari

In [43]:
data[["model", "transmission", "price"]].groupby(["model", "transmission"]).count()

                     price
model  transmission
lounge automatic        19
       manual          193
pop    automatic         4
       manual           98
sport  automatic         2
       manual           63
star   manual            1

### Modo per fare il group by veloce

In [44]:
data[["model", "transmission"]].value_counts()

model   transmission
lounge  manual          193
pop     manual           98
sport   manual           63
lounge  automatic        19
pop     automatic         4
sport   automatic         2
star    manual            1
Name: count, dtype: int64